### ISSUE TITLE
Set up ApeWorx for testing

### ISSUE THREAD

**Issue by jmonteer** [jmonteer/yearn-vaults-v3#11]
Set up ApeWorx
------
#### Short Description:
To be able to use ApeWorx, we need to set up the framework for tests to be written. This includes choosing the right test structure and writting fixtures for the tests to be easy to write. An utils folder is also important to be correctly thought so we can reuse as much code as possible. 

#### Details

See: 
- V2 version of tests: https://github.com/yearn/yearn-vaults/tree/main/tests
- V3 first version: https://github.com/saltyfacu/vaults-hardhat/tree/develop/test
- fancy things like parametrized fixtures, utils, actions, ... (Joint strategy repo) https://github.com/fp-crypto/joint-strategy/tree/fp-univ3/tests

The objective is to create a folder structure that complies with our plans: 
- e2e testing
- unit testing
- utils (these may be specific to e2e or unit testing) so may make sense to split inside or move into the other folders

In the utils folders, it may make sense to separate in:
- utils: the functions to do accounting, conversions, ...
- actions: user / permissioned accounts actions that are used in all the tests: deposits, withdraws, transfers, ...
- checks: checks that are used several times: check that pps is up / down, check a vault is withdrawable, ...

Each folder should have its own conftest.py with the right fixtures within it. 

#### Dependencies:
NA

#### Acceptance criteria:
- Folder structure with tests
- Implemented utils / actions / checks folders
- Created conftest.py for e2e and unit tests
- Created basic user-facing unit tests we know how they should behave: deposit and withdraw
- Created basic happy path e2e test

#### Payment Trigger:
PR is merged

#### Category:
DEV

#### Level:**
2

**Comment by pandadefi** [comment]
Have a look at https://github.com/yearn/veYFI/tree/master/tests/functional should be pretty much the same base.

**Comment by jmonteer** [comment]
@anticlimactic can you assign yourself here?

**Comment by jmonteer** [comment]
closed by #14
