### ISSUE TITLE
Create tests for strategy management functions

### ISSUE THREAD

**Issue by jmonteer** [jmonteer/yearn-vaults-v3#21]
Create tests for strategy management functions
------
**Description:** 
We need tests for strategy management functions. There's a short list here: 
#20 
**Dependencies:**
NA
**Acceptance criteria:** 
Tests are written and passing
**Payment Trigger:** 
PR is merged
**Category:**
DEV
**Level:**
1

**Comment by anticlimactic** [comment]
closing as merged
