### ISSUE TITLE
rename amount in VaultV3.vy to asset to be consistent with ERC4626 standard

### ISSUE THREAD

**Issue by anticlimactic** [jmonteer/yearn-vaults-v3#36]
see title:

even if we choose to implement erc4626 separately, having the vault call it "amount" and "shares" vs. erc4626 calling it "asset" and "shares" adds cognitive burden to people reading/reviewing the code.

i propose changing reference to `amount` to `asset` in the vault code.

**Comment by jmonteer** [comment]
closed by #24 / #30
