### ISSUE TITLE
Tests for Role based access 

### ISSUE THREAD

**Issue by jmonteer** [jmonteer/yearn-vaults-v3#45]
Tests for Role based access 
------
**Description:** 
Ensure that all permissioned functions are under role enforcement in one of the following three roles: 
- DEBT_MANAGER: updateDebt and setters
- STRATEGY_MANAGER: add remove and migrate strategies and their setters
- ACCOUNTING_MANAGER: process reports

Also, ensure that the governance role can do role changes successfully. 

**Dependencies:**
Bounty #44  is done

**Acceptance criteria:** 
All tests are implemented and running. 
¡
**Payment Trigger:** 
PR is merged
**Category:**
DEV
**Level:**
1

**Comment by bufander** [comment]
Fair enough. I will use existing accounts
